services:
  - type: web
    name: wa-drive
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
