services:
  - type: web
    name: wa-drive
    runtime: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: "*"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
