apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybercontrol

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - extension-service.yaml
  - whatsapp-service.yaml
  - whatsapp-resolver.yaml
  - frontend.yaml
  - ingress.yaml
