apiVersion: v1
kind: Secret
metadata:
  name: cybercontrol-secrets
  namespace: cybercontrol
type: Opaque
stringData:
  DB_PASSWORD: "cybercontrol123"
  DATABASE_URL: "postgresql://cybercontrol_app:cybercontrol123@postgres:5432/cybercontrol"
  JWT_SECRET: "cybercontrol-jwt-secret-2024"
  JWT_REFRESH_SECRET: "UfklGtkG+8Y7EuRnHr/c48ANolQPMJgHhLVUDqCB/7xZZ3gnTHIiktKEpaWU6eER"
  WA_SECRET: "wa-service-secret-2024"
  GROQ_API_KEY: "CHANGEME"
  GOOGLE_CLIENT_ID: "CHANGEME"
  GOOGLE_CLIENT_SECRET: "CHANGEME"
  GOOGLE_REDIRECT_URI: "https://api.cybercontrol.fun/api/drive/callback"
