/**
 * sequential fill â€” solid closure (no AsyncFunction).
 * AUTO-generated by _rebuild-sequential-solid.mjs from _source_snapshot.js
 */
(function (root) {
  'use strict';
  root.CcExecParts = root.CcExecParts || {};
  root.CcExecParts.installSequential = function (k) {
    const b = root.CcExecParts.bindKernelLocals(k);
    const portalAdapters = b.portalAdapters;
    const filledBySource = b.filledBySource;
    const mapping = b.mapping;
    const _replayResults = b._replayResults;
    const _ccRecords = b._ccRecords;
    const RUNTIME_VERSION = b.RUNTIME_VERSION;
    const _CC_USE_PLUGINS = b._CC_USE_PLUGINS;
    const PRIORITY_KEYS = b.PRIORITY_KEYS;
    const entries = b.entries;
    const getEl = b.getEl;
    const _emitFillDebug = b._emitFillDebug;
    const _flushRecords = b._flushRecords;
    const _pushSelectRecord = b._pushSelectRecord;
    const settleAfterAct = b.settleAfterAct;
    const waitForSelectOptionsSequential = b.waitForSelectOptionsSequential;
    const waitForOptions = b.waitForOptions;
    const waitForDOMQuiet = b.waitForDOMQuiet || function (ms) {
      return new Promise(function (r) { setTimeout(r, ms || 300); });
    };
    const waitForNetworkIdle = b.waitForNetworkIdle || function (q, m) {
      return (window.ccWaitForNetworkIdle
        ? window.ccWaitForNetworkIdle(q || 200, m || 8000)
        : Promise.resolve({ idle: true, waitedMs: 0 }));
    };
    const detectStrategy = b.detectStrategy;
    const verifyValue = b.verifyValue;
    const _isPlaceholderOption = b._isPlaceholderOption;
    const _realOptions = b._realOptions;
    const _sampleOptions = b._sampleOptions;
    const _readSelectActual = b._readSelectActual;
    const _selectLoadMode = b._selectLoadMode;
    const _cascadeSemanticKey = b._cascadeSemanticKey;
    const _CASCADE_PARENTS = b._CASCADE_PARENTS;
    const _cascadeSettled = b._cascadeSettled;
    const _isPlaceholderPlanned = b._isPlaceholderPlanned;
    const _selectIsActive = b._selectIsActive;
    const fillOne = b.fillOne;

    // Mark kernel ready (compat with older facade checks)
    k._seqChunks = k._seqChunks || ['baked-solid'];

    k.fillSequential = async function fillSequential() {
          for (const [selector, fieldData] of entries) {
            const { value, type } = fieldData;
            let isNgDropdown = type === 'ng-dropdown' || selector.startsWith('ng-dropdown-');
            const fieldLabel = (filledBySource[selector]?.label || selector).toLowerCase();
            const _fieldCtxEarly = filledBySource[selector] || {};
            _emitFillDebug('field.start', {
              selector,
              label: _fieldCtxEarly.label || fieldLabel,
              type,
              planned: value,
              profileKey: _fieldCtxEarly.profileKey || fieldData.profileKey || null,
            });
            const _selectLike = /^(select|dropdown|ng-dropdown|mat-select)$/.test(type || '');
            const isDependent = _selectLike && PRIORITY_KEYS.some((pk) => fieldLabel.includes(pk) || selector.toLowerCase().includes(pk));
            let el;
            if (selector.startsWith('form-field-')) {
              const all = document.querySelectorAll('input[type="text"],input[type="email"],input[type="tel"],input[type="number"],input[type="date"],input[type="radio"],input[type="checkbox"],input:not([type]),textarea,select');
              el = all[parseInt(selector.split('-')[2])];
            } else if (selector.startsWith('ng-dropdown-')) {
              el = document.querySelectorAll('div.ng-dropdown')[parseInt(selector.split('-')[2])];
            } else {
              el = document.querySelector(selector);
            }
            if (!isNgDropdown && el) {
              const _tag = el.tagName.toLowerCase();
              if (_tag === 'ng-select' || (el.classList && (el.classList.contains('ng-select') || el.classList.contains('ng-dropdown')))) {
                isNgDropdown = true;
              }
              if (!isNgDropdown && _tag !== 'select' && _tag !== 'input' && _tag !== 'mat-select') {
                const _role = el.getAttribute('role');
                if (_role === 'combobox' || _role === 'listbox') isNgDropdown = true;
              }
            }
            if (el) {
              el.scrollIntoView({ behavior: 'smooth', block: 'center' });
              await new Promise(r => setTimeout(r, 300));
            }
            const _t0 = Date.now();
            const _fieldCtx = {
              type,
              label: fieldData.label || filledBySource[selector]?.label || selector,
              profileKey: fieldData.profileKey || filledBySource[selector]?.profileKey || '',
              selector,
              matchBy: fieldData.matchBy || filledBySource[selector]?.matchBy || 'label',
            };
            const _selectLike2 = /^(select|dropdown|ng-dropdown|mat-select)$/.test(type || '');
            if (_selectLike2) console.log('[CC] route:', selector, 'type:', type, 'isNgDropdown:', isNgDropdown, 'isDependent:', isDependent, 'filled:', k.filled, 'elTag:', el?.tagName, 'elType:', el?.type);
            if (fieldData.type === 'button') {
              const _btnPlugin = (_CC_USE_PLUGINS && typeof findPlugin === 'function') ? findPlugin(el, _fieldCtx) : null;
              if (_btnPlugin) {
                const _pResult = _btnPlugin.fill(el, value, { attempt: 1 });
                const _preCount = document.querySelectorAll("input,select,textarea,div.ng-dropdown").length;
                await waitForDOMQuiet(800);
                const newFields = document.querySelectorAll('input[type="text"],input[type="email"],input[type="tel"],input[type="number"],input[type="date"],input[type="radio"],input[type="checkbox"],input:not([type]),textarea,select,div.ng-dropdown');
                const newFieldCount = newFields.length;
                _ccRecords.push({ selector, value, type: 'button', result: 'filled', strategy: 'plugin:button-click', plugin: 'button-click', role: fieldData.role || 'navigation', newFieldCount, transitionOutcome: newFieldCount > _preCount ? "transition_success" : newFieldCount === _preCount ? "transition_no_change" : "transition_partial", durationMs: Date.now()-_t0, ts: Date.now(), rv: RUNTIME_VERSION, fillMode: 'sequential' }); _flushRecords();
                console.debug('[CC][plugin] button-click', selector, 'newFields:', newFieldCount);
              } else {
                if (el) el.click();
                await waitForDOMQuiet(800);
              }
              await settleAfterAct('button');
            } else if (isNgDropdown) {
              if (!el) { _ccRecords.push({ selector, value, type, result: 'skipped', failReason: 'no-element', strategy: 'ng-dropdown', ts: Date.now(), rv: RUNTIME_VERSION }); _flushRecords(); continue; }
              if (_realOptions(el).length === 0 && el.tagName === 'SELECT') {
                el = (await waitForSelectOptionsSequential(selector, 5000)) || el;
              }
              const _ngPlugin = (_CC_USE_PLUGINS && typeof findPlugin === 'function') ? findPlugin(el, _fieldCtx) : null;
              if (_ngPlugin) {
                try {
                  const _ctx = { profileKey: _fieldCtx.profileKey, portalAdapters: portalAdapters || {}, attempt: 1 };
                  const _pResult = await _ngPlugin.fill(el, value, _ctx);
                  const _r = _pResult.success ? 1 : 0;
                  k.filled += _r;
                  _ccRecords.push({ selector, value, type, result: _r ? 'filled' : 'skipped', failReason: _r ? null : _pResult.reason, strategy: 'plugin:' + _ngPlugin.id, plugin: _ngPlugin.id, durationMs: Date.now()-_t0, ts: Date.now(), rv: RUNTIME_VERSION, fillMode: 'sequential' }); _flushRecords();
                } catch(e) {
                  fillOne(selector, value, type);
                }
              } else {
                fillOne(selector, value, type);
              }
              await settleAfterAct('select');
            } else if (_selectLike && el && el.tagName === 'SELECT') {
              const semKey = _cascadeSemanticKey(_fieldCtx.label, _fieldCtx.profileKey, selector);
              let liveEl = el;
              let loadMode = _selectLoadMode(liveEl);
              let optionCountBefore = _realOptions(liveEl).length;
              let sampleBefore = _sampleOptions(liveEl);
              let settleMeta = { idle: true, waitedMs: 0 };
              if (_isPlaceholderPlanned(value)) {
                _pushSelectRecord({
                  selector, value, type, label: _fieldCtx.label, profileKey: _fieldCtx.profileKey || null,
                  result: 'skipped', failReason: 'placeholder_planned_value', strategy: 'sequential',
                  loadMode, actualValue: _readSelectActual(el).actualValue, durationMs: Date.now() - _t0,
                });
                continue;
              }
              if (!_selectIsActive(el) && loadMode === 'ajax') {
                _pushSelectRecord({
                  selector, value, type, label: _fieldCtx.label, profileKey: _fieldCtx.profileKey || null,
                  result: 'skipped', failReason: 'ajax_control_inactive', strategy: 'sequential',
                  loadMode: 'ajax', actualValue: '', durationMs: Date.now() - _t0,
                });
                continue;
              }
              if (_realOptions(liveEl).length === 0) {
                const exhausted = k.ajaxWaitBudgetMs <= 0 || k.ajaxNotLoadedCount >= 5;
                const cap = exhausted ? 500 : Math.min(6000, Math.max(500, k.ajaxWaitBudgetMs));
                console.log('[CC] sequential-wait-options:', selector, 'budget=', k.ajaxWaitBudgetMs, 'cap=', cap);
                const waitedEl = await waitForSelectOptionsSequential(selector, cap);
                liveEl = waitedEl || document.querySelector(selector) || el;
                loadMode = _selectLoadMode(liveEl);
                if (_realOptions(liveEl).length === 0) {
                  k.ajaxNotLoadedCount += 1;
                  _pushSelectRecord({
                    selector, value, type, label: _fieldCtx.label, profileKey: _fieldCtx.profileKey || null,
                    result: 'skipped',
                    failReason: exhausted ? 'ajax_wait_budget_exhausted' : 'strategy_options_not_ready',
                    strategy: 'sequential',
                    loadMode: 'ajax',
                    optionCount: 0,
                    optionSample: _sampleOptions(liveEl, 8),
                    actualValue: _readSelectActual(liveEl).actualValue,
                    durationMs: Date.now() - _t0,
                  });
                  continue;
                }
              }
              optionCountBefore = _realOptions(liveEl).length;
              sampleBefore = _sampleOptions(liveEl, 10);
              let strategy = 'native-select';
              let attempt = 1;
              async function tryApply(attemptNo) {
                const _plugin =
                  _CC_USE_PLUGINS && typeof findPlugin === 'function' ? findPlugin(liveEl, _fieldCtx) : null;
                if (_plugin) {
                  const _pResult = _plugin.fill(liveEl, value, {
                    profileKey: _fieldCtx.profileKey,
                    attempt: attemptNo,
                  });
                  strategy = 'plugin:' + _plugin.id;
                  if (_pResult && _pResult.success) return { ok: true, reason: null };
                  return {
                    ok: false,
                    reason: (_pResult && _pResult.reason) || 'strategy_option_mismatch',
                    optionCount: _pResult && _pResult.optionCount,
                  };
                }
                const _r = fillOne(selector, value, type) || 0;
                strategy = 'native-select';
                if (_r) return { ok: true, reason: null };
                const real = _realOptions(liveEl);
                if (!real.length) return { ok: false, reason: 'strategy_options_not_ready' };
                return { ok: false, reason: 'strategy_option_mismatch', optionCount: real.length };
              }
              let applyRes = await tryApply(1);
              if (!applyRes.ok && k.ajaxWaitBudgetMs > 2000 && k.ajaxNotLoadedCount < 3) {
                attempt = 2;
                await settleAfterAct('select', { budgetMs: 2500 });
                liveEl = document.querySelector(selector) || liveEl;
                if (_realOptions(liveEl).length > 0) applyRes = await tryApply(2);
              }
              settleMeta = await settleAfterAct('select');
              liveEl = document.querySelector(selector) || liveEl;
              const actual = _readSelectActual(liveEl);
              let matchOk = applyRes.ok;
              if (!matchOk && actual.actualValue && value) {
                const np = String(value).toLowerCase().replace(/[^a-z0-9]/g, '');
                const na = String(actual.actualValue).toLowerCase().replace(/[^a-z0-9]/g, '');
                if (np && na && (np === na || na.includes(np) || np.includes(na))) matchOk = true;
              }
              if (matchOk) {
                k.filled += 1;
                if (semKey) {
                  _cascadeSettled[semKey] = {
                    key: semKey,
                    selector,
                    value,
                    actualValue: actual.actualValue,
                  };
                }
              } else if (applyRes.reason === 'strategy_options_not_ready' || applyRes.reason === 'ajax_options_not_loaded') {
                k.ajaxNotLoadedCount += 1;
              }
              _pushSelectRecord({
                selector,
                value,
                type,
                label: _fieldCtx.label,
                profileKey: _fieldCtx.profileKey || null,
                result: matchOk ? 'filled' : 'skipped',
                failReason: matchOk ? null : (applyRes.reason || 'strategy_failed'),
                strategy,
                loadMode,
                optionCount: _realOptions(liveEl).length,
                optionSample: _sampleOptions(liveEl, 10),
                optionSampleBefore: sampleBefore,
                optionCountBefore,
                actualValue: actual.actualValue,
                actualOptionValue: actual.actualOptionValue,
                verified: matchOk,
                attempt,
                waitedMs: settleMeta.waitedMs,
                networkIdle: settleMeta.idle,
                durationMs: Date.now() - _t0,
              });
            } else if (el && el.type === 'file') {
              if (value && (value.startsWith('http://') || value.startsWith('https://'))) {
                try {
                  const resp = await fetch(value);
                  if (resp.ok) {
                    const blob = await resp.blob();
                    const fileName = value.split('/').pop().split('?')[0] || 'document';
                    const file = new File([blob], fileName, {
                      type: blob.type || 'application/octet-stream',
                      lastModified: Date.now(),
                    });
                    const dt = new DataTransfer();
                    dt.items.add(file);
                    el.files = dt.files;
                    el.dispatchEvent(new Event('change', { bubbles: true }));
                    k.filled += 1;
                    console.debug('[CC] file URL assigned:', selector, fileName, file.size, 'bytes');
                    _ccRecords.push({
                      selector,
                      value,
                      type: 'file',
                      label: _fieldCtx.label,
                      result: 'filled',
                      strategy: 'file-url-fetch',
                      fileName,
                      fileSize: file.size,
                      fillMode: 'sequential',
                      durationMs: Date.now() - _t0,
                      ts: Date.now(),
                      rv: RUNTIME_VERSION,
                    });
                    _flushRecords();
                  } else {
                    _ccRecords.push({
                      selector,
                      value,
                      type: 'file',
                      label: _fieldCtx.label,
                      result: 'waiting_human',
                      failReason: 'fetch-' + resp.status,
                      strategy: 'file-needs-human',
                      fillMode: 'sequential',
                      durationMs: Date.now() - _t0,
                      ts: Date.now(),
                      rv: RUNTIME_VERSION,
                    });
                    _flushRecords();
                  }
                } catch (e) {
                  _ccRecords.push({
                    selector,
                    value,
                    type: 'file',
                    label: _fieldCtx.label,
                    result: 'waiting_human',
                    failReason: e.message || 'fetch-error',
                    strategy: 'file-needs-human',
                    fillMode: 'sequential',
                    durationMs: Date.now() - _t0,
                    ts: Date.now(),
                    rv: RUNTIME_VERSION,
                  });
                  _flushRecords();
                }
              } else {
                _ccRecords.push({
                  selector,
                  value: value || null,
                  type: 'file',
                  label: _fieldCtx.label,
                  result: 'waiting_human',
                  failReason: value ? 'filename_only_no_url' : 'no_file_value',
                  strategy: 'file-needs-human',
                  fillMode: 'sequential',
                  durationMs: Date.now() - _t0,
                  ts: Date.now(),
                  rv: RUNTIME_VERSION,
                });
                _flushRecords();
              }
              await settleAfterAct('text');
            } else {
              const isChoice =
                type === 'radio-click' ||
                type === 'radio' ||
                type === 'radio-group' ||
                type === 'checkbox' ||
                type === 'mat-checkbox' ||
                type === 'mat-radio' ||
                (el && (el.type === 'radio' || el.type === 'checkbox'));
              try {
                const _r = fillOne(selector, value, type) || 0;
                if (isChoice) await settleAfterAct('choice');
                else await settleAfterAct('text');
                const _el2 = el || document.querySelector(selector);
                const _strategy = detectStrategy(_el2, type);
                const _ver = await verifyValue(selector, value, isChoice ? 80 : 100);
                let _trulyFilled = false;
                if (isChoice && _r === 1) {
                  if (_el2 && (_el2.type === 'radio' || _el2.type === 'checkbox')) {
                    _trulyFilled = !!_el2.checked;
                  } else {
                    _trulyFilled = _ver.ok || _r === 1;
                  }
                  if (!_trulyFilled && _ver.actualValue === 'true') _trulyFilled = true;
                } else {
                  _trulyFilled = _r === 1 && _ver.ok;
                }
                if (_trulyFilled) k.filled += 1;
                const _recChoice = {
                  selector,
                  value,
                  type,
                  label: _fieldCtx.label,
                  profileKey: _fieldCtx.profileKey || null,
                  result: _trulyFilled ? 'filled' : 'skipped',
                  failReason: _trulyFilled
                    ? null
                    : _r
                      ? _ver.reason || 'strategy_failed'
                      : _el2
                        ? 'strategy_failed'
                        : 'no-element',
                  actualValue: _ver.actualValue,
                  verified: _trulyFilled,
                  strategy: _strategy,
                  matchBy: _fieldCtx.matchBy,
                  fillMode: 'sequential',
                  durationMs: Date.now() - _t0,
                  ts: Date.now(),
                  rv: RUNTIME_VERSION,
                };
                _ccRecords.push(_recChoice);
                _flushRecords();
                _emitFillDebug(_trulyFilled ? 'field.done' : 'field.fail', {
                  selector,
                  label: _fieldCtx.label,
                  type,
                  planned: value,
                  actual: _ver.actualValue,
                  failReason: _recChoice.failReason,
                  strategy: _strategy,
                });
              } catch (e) {
                _ccRecords.push({
                  selector,
                  value,
                  type,
                  result: 'error',
                  error: e.message,
                  fillMode: 'sequential',
                  ts: Date.now(),
                  rv: RUNTIME_VERSION,
                });
                _flushRecords();
                _emitFillDebug('field.fail', {
                  selector,
                  type,
                  planned: value,
                  failReason: e.message || 'error',
                });
              }
            }
          }
    };
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
